# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  order.gdzce.cn:
    container_name: order.gdzce.cn
    extends:
      service: orderer-base
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order.gdzce.cn/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order.gdzce.cn/tls/:/var/hyperledger/orderer/tls
        - order.gdzce.cn:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  node1.organization1.gdzce.cn:
    container_name: node1.organization1.gdzce.cn
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=node1.organization1.gdzce.cn
      - CORE_PEER_ADDRESS=node1.organization1.gdzce.cn:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=node1.organization1.gdzce.cn:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=node2.organization1.gdzce.cn:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node1.organization1.gdzce.cn:7051
      - CORE_PEER_LOCALMSPID=Organization1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/tls:/etc/hyperledger/fabric/tls
        - node1.organization1.gdzce.cn:/var/hyperledger/production
    ports:
      - 7051:7051

  node2.organization1.gdzce.cn:
    container_name: node2.organization1.gdzce.cn
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=node2.organization1.gdzce.cn
      - CORE_PEER_ADDRESS=node2.organization1.gdzce.cn:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=node2.organization1.gdzce.cn:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node2.organization1.gdzce.cn:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node1.organization1.gdzce.cn:7051
      - CORE_PEER_LOCALMSPID=Organization1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/organization1.gdzce.cn/peers/node2.organization1.gdzce.cn/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/organization1.gdzce.cn/peers/node2.organization1.gdzce.cn/tls:/etc/hyperledger/fabric/tls
        - node2.organization1.gdzce.cn:/var/hyperledger/production

    ports:
      - 8051:8051

  node1.organization2.gdzce.cn:
    container_name: node1.organization2.gdzce.cn
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=node1.organization2.gdzce.cn
      - CORE_PEER_ADDRESS=node1.organization2.gdzce.cn:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=node1.organization2.gdzce.cn:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node1.organization2.gdzce.cn:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node2.organization2.gdzce.cn:10051
      - CORE_PEER_LOCALMSPID=Organization2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/organization2.gdzce.cn/peers/node1.organization2.gdzce.cn/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/organization2.gdzce.cn/peers/node1.organization2.gdzce.cn/tls:/etc/hyperledger/fabric/tls
        - node1.organization2.gdzce.cn:/var/hyperledger/production
    ports:
      - 9051:9051

  node2.organization2.gdzce.cn:
    container_name: node2.organization2.gdzce.cn
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=node2.organization2.gdzce.cn
      - CORE_PEER_ADDRESS=node2.organization2.gdzce.cn:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=node2.organization2.gdzce.cn:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node2.organization2.gdzce.cn:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node1.organization2.gdzce.cn:9051
      - CORE_PEER_LOCALMSPID=Organization2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/organization2.gdzce.cn/peers/node2.organization2.gdzce.cn/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/organization2.gdzce.cn/peers/node2.organization2.gdzce.cn/tls:/etc/hyperledger/fabric/tls
        - node2.organization2.gdzce.cn:/var/hyperledger/production
    ports:
      - 10051:10051

  node1.organization3.gdzce.cn:
    container_name: node1.organization3.gdzce.cn
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=node1.organization3.gdzce.cn
      - CORE_PEER_ADDRESS=node1.organization3.gdzce.cn:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=node1.organization3.gdzce.cn:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node1.organization3.gdzce.cn:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node2.organization3.gdzce.cn:12051
      - CORE_PEER_LOCALMSPID=Organization3MSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/organization3.gdzce.cn/peers/node1.organization3.gdzce.cn/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/organization3.gdzce.cn/peers/node1.organization3.gdzce.cn/tls:/etc/hyperledger/fabric/tls
      - node1.organization3.gdzce.cn:/var/hyperledger/production
    ports:
      - 11051:11051

  node2.organization3.gdzce.cn:
    container_name: node2.organization3.gdzce.cn
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=node2.organization3.gdzce.cn
      - CORE_PEER_ADDRESS=node2.organization3.gdzce.cn:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=node2.organization3.gdzce.cn:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=node2.organization3.gdzce.cn:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=node1.organization3.gdzce.cn:11051
      - CORE_PEER_LOCALMSPID=Organization3MSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/organization3.gdzce.cn/peers/node2.organization3.gdzce.cn/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/organization3.gdzce.cn/peers/node2.organization3.gdzce.cn/tls:/etc/hyperledger/fabric/tls
      - node2.organization3.gdzce.cn:/var/hyperledger/production
    ports:
      - 12051:12051

  peer-base:
    image: hyperledger/fabric-peer
    restart: always
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=deploy_byfn
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

  orderer-base:
    image: hyperledger/fabric-orderer
    restart: always
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer