# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  order.gdzce.cn:
  order2.gdzce.cn:
  order3.gdzce.cn:
  order4.gdzce.cn:
  order5.gdzce.cn:
  node1.organization1.gdzce.cn:
  node2.organization1.gdzce.cn:
  node1.organization2.gdzce.cn:
  node2.organization2.gdzce.cn:
  node1.organization3.gdzce.cn:
  node2.organization3.gdzce.cn:

networks:
  byfn:

services:

  order.gdzce.cn:
    extends:
      file: docker-compose-base.yaml
      service: order.gdzce.cn
    container_name: order.gdzce.cn
    networks:
      - byfn
  order2.gdzce.cn:
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    container_name: order2.gdzce.cn
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order2.gdzce.cn/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order2.gdzce.cn/tls/:/var/hyperledger/orderer/tls
      - order2.gdzce.cn:/var/hyperledger/production/orderer
    ports:
      - 8050:7050

  order3.gdzce.cn:
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    container_name: order3.gdzce.cn
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order3.gdzce.cn/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order3.gdzce.cn/tls/:/var/hyperledger/orderer/tls
      - order3.gdzce.cn:/var/hyperledger/production/orderer
    ports:
      - 9050:7050

  order4.gdzce.cn:
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    container_name: order4.gdzce.cn
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order4.gdzce.cn/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order4.gdzce.cn/tls/:/var/hyperledger/orderer/tls
      - order4.gdzce.cn:/var/hyperledger/production/orderer
    ports:
      - 10050:7050

  order5.gdzce.cn:
    extends:
      file: docker-compose-base.yaml
      service: orderer-base
    container_name: order5.gdzce.cn
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order5.gdzce.cn/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/gdzce.cn/orderers/order5.gdzce.cn/tls/:/var/hyperledger/orderer/tls
      - order5.gdzce.cn:/var/hyperledger/production/orderer
    ports:
      - 11050:7050
  node1.organization1.gdzce.cn:
    container_name: node1.organization1.gdzce.cn
    extends:
      file:  docker-compose-base.yaml
      service: node1.organization1.gdzce.cn
    networks:
      - byfn

  node2.organization1.gdzce.cn:
    container_name: node2.organization1.gdzce.cn
    extends:
      file:  docker-compose-base.yaml
      service: node2.organization1.gdzce.cn
    networks:
      - byfn

  node1.organization2.gdzce.cn:
    container_name: node1.organization2.gdzce.cn
    extends:
      file:  docker-compose-base.yaml
      service: node1.organization2.gdzce.cn
    networks:
      - byfn

  node2.organization2.gdzce.cn:
    container_name: node2.organization2.gdzce.cn
    extends:
      file:  docker-compose-base.yaml
      service: node2.organization2.gdzce.cn
    networks:
      - byfn

  node1.organization3.gdzce.cn:
    container_name: node1.organization3.gdzce.cn
    extends:
      file:  docker-compose-base.yaml
      service: node1.organization3.gdzce.cn
    networks:
      - byfn

  node2.organization3.gdzce.cn:
    container_name: node2.organization3.gdzce.cn
    extends:
      file:  docker-compose-base.yaml
      service: node2.organization3.gdzce.cn
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    restart: always
    environment:
      - SYS_CHANNEL=syschannel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=node1.organization1.gdzce.cn:7051
      - CORE_PEER_LOCALMSPID=Organization1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/organization1.gdzce.cn/peers/node1.organization1.gdzce.cn/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/organization1.gdzce.cn/users/Admin@organization1.gdzce.cn/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - order.gdzce.cn
      - node1.organization1.gdzce.cn
      - node2.organization1.gdzce.cn
      - node1.organization2.gdzce.cn
      - node2.organization2.gdzce.cn
      - node1.organization3.gdzce.cn
      - node2.organization3.gdzce.cn
    networks:
      - byfn
